### ISSUE TITLE
No rule to make target '/examples/make.mk

### ISSUE THREAD

**Issue by simooon442** [arduino/arduino-renesas-bootloader#1]
It seems a folder (examples) containing à "make.mk" is missing when we try to **make** file.

`C:\Users\PC\Downloads\arduino-renesas-bootloader-main\arduino-renesas-bootloader-main>make -f Makefile.minima
Makefile.minima:8: /examples/make.mk: No such file or directory
make: *** No rule to make target '/examples/make.mk'.  Stop.`

Is it normal ?

**Comment by facchinm** [comment]
Hi @simooon442 ,
you need to clone tinyusb somewhere and specify [TINYUSB_ROOT](https://github.com/arduino/arduino-renesas-bootloader/blob/main/compile.sh#L4) env variable to properly compile the bootloaders :wink:
