### ISSUE TITLE
Recompilation of the dfu_minima.hex not identical as the standard one

### ISSUE THREAD

**Issue by SimWorld-code** [arduino/arduino-renesas-bootloader#5]
I try to give a go to recompile the bootloader to get a small variation of the VID/PID inside.
To make it simple my approach was first to recompile exactly the main code without modification.

I tried with different version of Tinyusb 0.15, 0.16, 0.17 with the small variation of codes needed depending where are the make.mk

It seems i tried to compile with the 0.16 and 0.17 but the .hex that i output is somehow not the same than the original one, sligthly smaller 30Ko instead of 35Ko

Is there any recommendation in term of the version of TinyUSB to use ? Or any other software version to be careful about ?

Here the output of the compilation :
<details><summary>Details</summary>
<p>

PS C:\Users\Peuge\Documents\bootloader> make -f Makefile.minima
"Using PORT 0 FullSpeed"
CC dcd_rusb2.o
CC hcd_rusb2.o
CC rusb2_common.o
CC startup.o
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/bsp/cmsis/Device/RENESAS/Source/startup.c:133:5: warning: cast increases required alignment of target type [-Wcast-align]
  133 |     (exc_ptr_t) (&g_main_stack[0] + BSP_CFG_STACK_MAIN_BYTES), /*      Initial Stack Pointer     */
      |     ^
CC system.o
CC bsp_clocks.o
CC bsp_common.o
CC bsp_delay.o
CC bsp_group_irq.o
CC bsp_guard.o
CC bsp_io.o
CC bsp_irq.o
CC bsp_register_protection.o
CC bsp_rom_registers.o
CC bsp_sbrk.o
CC bsp_security.o
CC r_ioport.o
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_ioport/r_ioport.c: In function 'r_ioport_pins_config':
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_ioport/r_ioport.c:695:18: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
  695 |     p_pin_data = (ioport_cfg_t *) p_cfg;
      |                  ^
CC family.o
CC tusb.o
CC tusb_fifo.o
CC usbd.o
CC usbd_control.o
CC usbc.o
CC audio_device.o
CC cdc_device.o
CC dfu_device.o
CC dfu_rt_device.o
CC hid_device.o
CC midi_device.o
CC msc_device.o
CC ecm_rndis_device.o
CC ncm_device.o
CC usbtmc_device.o
CC video_device.o
CC vendor_device.o
CC usbh.o
CC hub.o
CC cdc_host.o
CC hid_host.o
CC msc_host.o
CC vendor_host.o
CC board.o
CC bossa.o
CC i2c_irq_c33.o
CC irq_table.o
CC main.o
In file included from c:/Users/Peuge/Documents/bootloader/src/main.c:34:
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/inc/instances/r_gpt.h:437:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
  437 | fsp_err_t R_GPT_PwmOutputDelayInitialize();
      | ^~~~~~~~~
c:/Users/Peuge/Documents/bootloader/src/main.c:50:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
   50 | void flash_ready_interrupt_handler();
      | ^~~~
c:/Users/Peuge/Documents/bootloader/src/main.c:51:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
   51 | void flash_error_interrupt_handler();
      | ^~~~
c:/Users/Peuge/Documents/bootloader/src/main.c:164:13: warning: function declaration isn't a prototype [-Wstrict-prototypes]
  164 | __WEAK void run_bootloader() {
      |             ^~~~~~~~~~~~~~
c:/Users/Peuge/Documents/bootloader/src/main.c: In function 'main':
c:/Users/Peuge/Documents/bootloader/src/main.c:118:46: warning: cast increases required alignment of target type [-Wcast-align]
  118 | #define BOOT_DOUBLE_TAP_DATA              (*((volatile uint32_t *) &R_SYSTEM->VBTBKR[0]))
      |                                              ^
c:/Users/Peuge/Documents/bootloader/src/main.c:184:7: note: in expansion of macro 'BOOT_DOUBLE_TAP_DATA'
  184 |   if (BOOT_DOUBLE_TAP_DATA == DOUBLE_TAP_MAGIC) {
      |       ^~~~~~~~~~~~~~~~~~~~
c:/Users/Peuge/Documents/bootloader/src/main.c: At top level:
c:/Users/Peuge/Documents/bootloader/src/main.c:299:5: warning: function declaration isn't a prototype [-Wstrict-prototypes]
  299 | int flash_write_block() {
      |     ^~~~~~~~~~~~~~~~~
c:/Users/Peuge/Documents/bootloader/src/main.c: In function 'tud_dfu_download_cb':
c:/Users/Peuge/Documents/bootloader/src/main.c:321:9: warning: unused variable 'err' [-Wunused-variable]
  321 |     int err = R_FLASH_LP_Erase(g_flash.p_ctrl, SKETCH_FLASH_OFFSET + (block_num * CFG_TUD_DFU_XFER_BUFSIZE), 1);
      |         ^~~
c:/Users/Peuge/Documents/bootloader/src/main.c: At top level:
c:/Users/Peuge/Documents/bootloader/src/main.c:403:6: warning: function declaration isn't a prototype [-Wstrict-prototypes]
  403 | void pulse_led()
      |      ^~~~~~~~~
c:/Users/Peuge/Documents/bootloader/src/main.c: In function 'set_double_tap_data':
c:/Users/Peuge/Documents/bootloader/src/main.c:118:46: warning: cast increases required alignment of target type [-Wcast-align]
  118 | #define BOOT_DOUBLE_TAP_DATA              (*((volatile uint32_t *) &R_SYSTEM->VBTBKR[0]))
      |                                              ^
c:/Users/Peuge/Documents/bootloader/src/main.c:444:3: note: in expansion of macro 'BOOT_DOUBLE_TAP_DATA'
  444 |   BOOT_DOUBLE_TAP_DATA = data;
      |   ^~~~~~~~~~~~~~~~~~~~
CC usb_descriptors.o
CC r_flash_lp.o
CC r_gpt.o
In file included from c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c:24:
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/inc/instances/r_gpt.h:437:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
  437 | fsp_err_t R_GPT_PwmOutputDelayInitialize();
      | ^~~~~~~~~
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c: In function 'R_GPT_Open':
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c:233:37: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
  233 |     gpt_extended_cfg_t * p_extend = (gpt_extended_cfg_t *) p_cfg->p_extend;
      |                                     ^
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c: In function 'R_GPT_Enable':
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c:359:37: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
  359 |     gpt_extended_cfg_t * p_extend = (gpt_extended_cfg_t *) p_instance_ctrl->p_cfg->p_extend;
      |                                     ^
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c: In function 'R_GPT_Close':
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c:1020:37: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
 1020 |     gpt_extended_cfg_t * p_extend = (gpt_extended_cfg_t *) p_instance_ctrl->p_cfg->p_extend;
      |                                     ^
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c: At top level:
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c:1058:11: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 1058 | fsp_err_t R_GPT_PwmOutputDelayInitialize ()
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c: In function 'gpt_hardware_initialize':
c:/Users/Peuge/Documents/tinyusb/hw/mcu/renesas/fsp/ra/fsp/src/r_gpt/r_gpt.c:1223:37: warning: cast discards 'const' qualifier from pointer target type [-Wcast-qual]
 1223 |     gpt_extended_cfg_t * p_extend = (gpt_extended_cfg_t *) p_cfg->p_extend;
      |                                     ^
LINK _build/uno_r4/bootloader.elf
Memory region         Used Size  Region Size  %age Used
            ITCM:          0 GB         0 GB
            DTCM:          0 GB         0 GB
           FLASH:       10788 B       256 KB      4.12%
             RAM:       10712 B        32 KB     32.69%
      DATA_FLASH:          0 GB         8 KB      0.00%
      QSPI_FLASH:          0 GB         0 GB
   OSPI_DEVICE_0:          0 GB         0 GB
   OSPI_DEVICE_1:          0 GB         0 GB
OSPI_DEVICE_0_RAM:          0 GB         0 GB
OSPI_DEVICE_1_RAM:          0 GB         0 GB
           SDRAM:          0 GB         0 GB
  OPTION_SETTING:          0 GB         0 GB
OPTION_SETTING_OFS:          0 GB         24 B      0.00%
OPTION_SETTING_SAS:          0 GB 4294967244 B      0.00%
OPTION_SETTING_S:          0 GB         0 GB
         ID_CODE:          28 B         32 B     87.50%
CREATE _build/uno_r4/bootloader.bin
arm-none-eabi-objcopy -O binary --only-section .text --only-section .data --only-section .rodata --only-section .bss _build/uno_r4/bootloader.elf _build/uno_r4/bootloader.bin
CREATE _build/uno_r4/bootloader.hex

   text    data     bss     dec     hex filename
  10816       0    9256   20072    4e68 _build/uno_r4/bootloader.elf

</p>
</details> 

Thanks

**Comment by facchinm** [comment]
Hi @SimWorld-code ,
a slight difference in code size is expected since the combination of compiler + tinyusb version might produce a substantially different  binary. For reference only, we've been compiling against [this tinyusb commit](https://github.com/arduino/tinyusb/tree/c796dcfe0bee337547437632dc16829038ef0f3d), which is the one we also use in the core https://github.com/arduino/ArduinoCore-renesas/tree/main/extras
